temp/objects/Insurance_Policy__c.object
<CustomObject>
    <fields>
        <fullName>Carrier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Carrier</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Carrier must be an insurance company</errorMessage>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Insurance Company, Risk Retention Group</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Insurance_Policy</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Insurance Submission</label>
    <nameField>
        <displayFormat>IP={0000000000}</displayFormat>
        <label>Insurance Policy</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance Submission</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AddressFieldController.cls
public class AddressFieldController {
  
    public Insurance_Policy__c record{get; private set;}
    public Account acct{get; private set;}
    
  public AddressFieldController(ApexPages.StandardController stdcontroller) {
    
     
      record = (Insurance_Policy__c)stdController.getRecord();
     // ID carrier = record.Carrier__c;
      
    //  acct = [SELECT Id, Name, BillingCountry, BillingPostalCode, BillingState, BillingCity, BillingStreet, 
           //   BillingLatitude, BillingLongitude 
           //  FROM Account WHERE Id = :carrier
         //  ]; 
  } 
}